### ISSUE TITLE
layca_update never be called :)

### ISSUE THREAD

**Issue by NigulasiChen** [vfdev-5/LayerRotation-pytorch#1]
i found that layca_update  never be called, maybe you should change
**class LaycaSGD(SGD):**

to:

class LaycaSGD(_BaseLaycaSGD):

**Comment by vfdev-5** [comment]
@NigulasiChen sorry for delay. Yes, seems like there is this should be a bug. Will fix it asap. Thanks for pointinh out !

**Comment by vfdev-5** [comment]
Fixed in https://github.com/vfdev-5/LayerRotation-pytorch/commit/97ea2ffac0c1f6e33d1b1a3a8c6271eb9823381e
